name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-readme:
    name: sync readme codes
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: run substitution
        run: |
          vimcmd="/default-config:start/+1,/default-config:end/-1y a |\
          e README.md |\
          /default-config:start/+2,/default-config:end/-2d |\
          /default-config:start/+1put a |\
          wq"; vim lua/rest-nvim/config/default.lua -c "$vimcmd"
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update README default config section"
          branch: ${{ github.ref }}

  release:
    name: release
    runs-on: ubuntu-latest
    needs: [sync-readme]
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.CI_TOKEN }}
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json
