name: format

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/**"
      - "**.md"

permissions:
  contents: write
  pull-requests: read

jobs:
  docgen:
    runs-on: ubuntu-latest
    name: Generate documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up lemmy-help
        uses: supplypike/setup-bin@v3
        with:
          uri: "https://github.com/numToStr/lemmy-help/releases/download/v0.11.0/lemmy-help-x86_64-unknown-linux-gnu.tar.gz"
          name: lemmy-help
          version: "0.11.0"
      - name: Generate docs
        run: "make docgen"
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: regenerate documentation"
          branch: ${{ github.ref }}
      - name: Push formatted files
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
