name: Luarocks release SCM

on:
  workflow_dispatch: # allows manual triggering
  # TODO: run on scm file has been changed

jobs:
  luarocks-upload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to count the commits
      - name: LuaRocks Upload SCM
        uses: nvim-neorocks/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          version: scm
          detailed_description: |
            rest.nvim makes use of Lua cURL bindings to make HTTP requests so you don't have to leave Neovim to test your back-end codebase!
          dependencies: |
            nvim-nio
            mimetypes
            xml2lua
            fidget.nvim
          test_dependencies: |
            nlua
          copy_directories: |
            {{ neovim.plugin.dirs }}
