name: Luarocks release
on:
  push:
    releases:
      types:
        - created
    tags:
      - "*"
  workflow_dispatch:

jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: Luarocks upload
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to count the commits
      - name: Install build dependencies
        run: sudo apt-get install -y libcurl4-gnutls-dev
      - name: Luarocks Upload
        uses: mrcjkb/luarocks-tag-release@v5
        with:
          dependencies: |
            nvim-nio
            lua-curl
            mimetypes
            xml2lua
          extra_luarocks_args: |
            CURL_INCDIR=/usr/include/x86_64-linux-gnu
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
