name: Luarocks release
on:
  push:
    tags:
      - "*"

jobs:
  luarocks-release:
    runs-on: ubuntu-latest
    name: Luarocks upload
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Luarocks Upload
        uses: mrcjkb/luarocks-tag-release@v5
        with:
          dependencies: |
            nvim-nio
            Lua-cURL
            mimetypes
            xml2lua
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
