name: Release Please Automatic Semver

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.CI_TOKEN }}
          release-type: simple
          package-name: rest.nvim
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.prs_created }}
      - name: Update Version String
        if: ${{ steps.release.outputs.prs_created }}
        run: |
          new_tag=${{ steps.release.outputs.tag_name }}

          echo "Updating \`rest.nvim\` Version to $new_tag"
          # sed -ri "s/api\.VERSION\s*=\s*\"[0-9\.\-]+\"$/api.VERSION = \"${new_tag:1}\"/" lua/rest-nvim/api.lua
      - name: Commit changes
        if: ${{ steps.release.outputs.prs_created }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(api.lua): update version variable"
          branch: ${{ github.ref }}
      - name: Push to Github
        if: ${{ steps.release.outputs.prs_created }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
